<?php

namespace Osiris\ApiBundle\Api;

use Ratchet\ConnectionInterface;

/**
* A two-device association.
*/
class Association
{
	/**
	 * @var ConnectionInterface
	 */
	protected $playerSocket;

	/**
	 * @var ConnectionInterface
	 */
	protected $mobileSocket;

	/**
	 * @var string
	 */
	protected $associationCode;

	/**
	 * @var string
	 */
	protected $facebookId;

	/**
	 * @var Boolean
	 */
	protected $completed;

    /**
     * Creates an Association object from a message.
     * Typically this message is a request for beginning an association,
     * using a facebook account ID or a simple code.
     */
	public static function createFromMessage(ConnectionInterface $from, Message $message)
	{
		$association = new static();
		$association->setCompleted(false);
		$association->setPlayerSocket($from);

		if ($message->getName() == MessageTypes::BEGIN_FACEBOOK_ASSOCIATION) {
			$association->setFacebookId($message->get('facebook_id'));

			echo "Client {$from->resourceId} initiated association with : FacebookID [{$association->getFacebookId()}]. Waiting for second device...\n";
			// ...
		} elseif ($message->getName() == MessageTypes::BEGIN_CODE_ASSOCIATION) {
			$association->setAssociationCode(Association::generateCode());

            $from->send(json_encode(array(
                'direction' => MessageTypes::BROADCAST,
                'name' => MessageTypes::ASSOCIATION_INITIATED_WITH_CODE,
                'data' => array(
                    'code' => $association->getAssociationCode(),
                ),
            )));

			echo "Client {$from->resourceId} initiated association with : code [{$association->getAssociationCode()}]. Waiting for second device...\n";
		}

		return $association;
	}

    /**
     * Generates a random numeric code for association.
     */
	public static function generateCode()
	{
		$alphabet = array('0','1','2','3','4','5','6','7','8','9');

		$code = '';

		for ($i = 0 ; $i <= 4 ; $i++) {
			$code .= $alphabet[mt_rand(0,9)];
		}

		return $code;
	}

    /**
     * Generates a token from a device association.
     * Once the association is made, the token is generated by
     * making a hash with the two devices sockets IDs.
     */
    public static function createToken(Association $association)
    {
        $playerSocketId = $association->getPlayerSocket()->resourceId;
        $mobileSocketId = $association->getMobileSocket()->resourceId;

        $token = md5($playerSocketId.'-'.$mobileSocketId);

        return $token;
    }

    /**
     * Completes a initiated association with a message from the second device.
     * This device is requesting for association with the first one.
     * If the two facebook IDs (or codes) matches, then the association is
     * successfully completed.
     */
	public function completeWithMessage(ConnectionInterface $from, Message $message)
	{
		if ($message->getName() == MessageTypes::ASSOCIATE_WITH_FACEBOOK) {
			$givenFacebookId = $message->get('facebook_id');
			
			if ($givenFacebookId == $this->getFacebookId()) {
				$this->setCompleted(true);
			}

		} elseif ($message->getName() == MessageTypes::ASSOCIATE_WITH_CODE) {
			$givenCode = $message->get('code');

			if ($givenCode == $this->getAssociationCode()) {
				$this->setCompleted(true);
			}
		}

		if ($this->getCompleted()) {
			$this->setMobileSocket($from);

			echo "Now associated with client {$from->resourceId}\n";

			return true;
		} else {
			return false;
		}
	}

    /**
     * Dispatches a message from one of the two devices to the another one.
     */
    public function dispatch(TokenizedMessage $message)
    {
        $jsonMessage = json_encode(array(
            'direction' => $message->getDirection(),
            'name' => $message->getName(),
            'data' => $message->getData(),
        ));

        if ($message->getDirection() == MessageTypes::FROM_PLAYER_TO_DEVICE) {
            $this->getMobileSocket()->send($jsonMessage);
        } else {
            $this->getPlayerSocket()->send($jsonMessage);
        }

        return true;
    }

    /**
     * Broadcast raw data to the two devices.
     */
    public function broadcast($data)
    {
        $this->getPlayerSocket()->send($data);
        $this->getMobileSocket()->send($data);
    }

    /**
     * Gets the value of playerSocket.
     *
     * @return ConnectionInterface
     */
    public function getPlayerSocket()
    {
        return $this->playerSocket;
    }

    /**
     * Sets the value of playerSocket.
     *
     * @param ConnectionInterface $playerSocket the player socket
     *
     * @return self
     */
    public function setPlayerSocket(ConnectionInterface $playerSocket)
    {
        $this->playerSocket = $playerSocket;

        return $this;
    }

    /**
     * Gets the value of mobileSocket.
     *
     * @return ConnectionInterface
     */
    public function getMobileSocket()
    {
        return $this->mobileSocket;
    }

    /**
     * Sets the value of mobileSocket.
     *
     * @param ConnectionInterface $mobileSocket the mobile socket
     *
     * @return self
     */
    public function setMobileSocket(ConnectionInterface $mobileSocket)
    {
        $this->mobileSocket = $mobileSocket;

        return $this;
    }

    /**
     * Gets the value of associationCode.
     *
     * @return string
     */
    public function getAssociationCode()
    {
        return $this->associationCode;
    }

    /**
     * Sets the value of associationCode.
     *
     * @param string $associationCode the association code
     *
     * @return self
     */
    public function setAssociationCode($associationCode)
    {
        $this->associationCode = $associationCode;

        return $this;
    }

    /**
     * Gets the value of facebookId.
     *
     * @return string
     */
    public function getFacebookId()
    {
        return $this->facebookId;
    }

    /**
     * Sets the value of facebookId.
     *
     * @param string $facebookId the facebook id
     *
     * @return self
     */
    public function setFacebookId($facebookId)
    {
        $this->facebookId = $facebookId;

        return $this;
    }

    /**
     * Gets the value of completed.
     *
     * @return Boolean
     */
    public function getCompleted()
    {
        return $this->completed;
    }

    /**
     * Sets the value of completed.
     *
     * @param Boolean $completed the completed
     *
     * @return self
     */
    public function setCompleted($completed)
    {
        $this->completed = $completed;

        return $this;
    }
}
